apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mytunes-ui
  name: mytunes-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytunes-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mytunes-ui
    spec:
      containers:
      - image: varunpadaki/mytunes:1.0
        imagePullPolicy: IfNotPresent
        name: mytunes-ui
        ports:
        - name: liveness-port
          containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
