apiVersion: v1
kind: Service
metadata:
  labels:
    app: mytunes-ui
  name: mytunes-ui
  namespace: default  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mytunes-ui
  sessionAffinity: None
  type: LoadBalancer
